name: "Deploy to python anywhere"

on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://kevinja.pythonanywhere.com/test"

    - name: Pull new code to pythonanywhere
      run: |
        curl -X POST "https://kevinja.pythonanywhere.com/git-update"

    - name: Reload pythonanywhere
      run: |
        curl -X POST -H "Authorization: Token ${{ secrets.PYTHON_ANYWHERE_ACCESS_TOKEN }}" "https://www.pythonanywhere.com/api/v0/user/kevinja/webapps/kevinja.pythonanywhere.com/reload/"
