name: "Hit a webhook"
 
on:
  push:
    branches:
      - master

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: REST API with curl
      run: |
        curl -X GET "https://kevinja.pythonanywhere.com/test"
